# ===============================================
# 🤖 AI助手集成工作流 (使用Gemini CLI v0.1.12)
# ===============================================
# 
# 🎯 用途：集成Gemini AI助手进行项目管理自动化
# 📋 功能：
#   - 自动PR代码审查 (AI驱动)
#   - Issue智能分类和标记
#   - 定时批量Issue处理
#   - @abc命令响应 (AI助手互动)
# 
# 🔗 依赖：ChenQiWen/gemini-cli-action 工作流
# 🤖 AI模型：Google Gemini API
# 🆕 版本：已修复JSON解析问题，强制JSON输出格式
# ===============================================

name: 🤖 AI智能助手集成管道

# 🚀 触发条件：多种GitHub事件
on:
  # 📋 拉取请求事件
  pull_request:
    types: [opened, reopened]  # PR开启或重新开启时触发
    
  # 🐛 Issue事件  
  issues:
    types: [opened]  # 新Issue创建时触发
    
  # 💬 评论事件
  issue_comment:
    types: [created]  # 新评论创建时触发
    
  # ⏰ 定时任务
  schedule:
    - cron: '0 5 * * *'  # 每天UTC时间5点执行 (北京时间13点)

jobs:
  # ===============================
  # 🚦 智能调度中心 (推荐使用)
  # ===============================
  # 注意: 如果你使用智能调度中心，可以替换下面的所有单独任务
  # 只需要一个调度中心就能处理所有AI功能
  # 使用方法: 将下面注释取消，并注释掉其他所有任务
  #
  # intelligent-dispatch:
  #   name: 🚦 AI助手统一调度
  #   uses: ChenQiWen/gemini-cli-action/.github/workflows/智能调度中心.yml@main
  #   secrets: inherit
  
  # ===============================
  # 📋 或者使用分离式任务 (当前配置)
  # ===============================
  # ===============================
  # 🔍 AI驱动的PR代码审查
  # ===============================
  代码审查任务:
    name: 🔍 AI驱动的代码审查
    # 🎯 条件：仅在PR事件时运行
    if: github.event_name == 'pull_request'
    
    # 🔐 权限配置：AI助手需要的最小权限集
    permissions:
      contents: 'read'        # 读取仓库内容
      id-token: 'write'       # 写入身份令牌
      issues: 'write'         # 写入Issue相关内容
      pull-requests: 'write'  # 写入PR相关内容
      statuses: 'write'       # 写入状态检查
    
    # 🔗 调用外部工作流：Gemini AI PR审查 (v0.1.12)
    uses: ChenQiWen/gemini-cli-action/.github/workflows/代码审查助手.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}  # 传递PR编号
    secrets: inherit  # 继承父仓库的所有secrets

  # ===============================
  # 🏷️ Issue智能自动分类
  # ===============================
  问题自动分类任务:
    name: 🏷️ 问题智能自动分类
    # 🎯 条件：仅在Issue创建事件时运行
    if: github.event_name == 'issues'
    
    # 🔐 权限配置：Issue处理所需权限
    permissions:
      contents: 'read'    # 读取仓库内容
      id-token: 'write'   # 写入身份令牌
      issues: 'write'     # 写入Issue (添加标签、分配等)
      statuses: 'write'   # 写入状态检查
    
    # 🔗 调用外部工作流：Gemini AI Issue自动分类 (已修复JSON格式问题)
    uses: ChenQiWen/gemini-cli-action/.github/workflows/问题自动分类器.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}  # Issue编号
      issue_title: ${{ github.event.issue.title }}    # Issue标题
      issue_body: ${{ github.event.issue.body }}      # Issue内容
    secrets: inherit

  # ===============================
  # 📅 定时批量Issue处理
  # ===============================
  问题定时分类任务:
    name: 📅 定时批量问题处理
    # 🎯 条件：仅在定时任务触发时运行
    if: github.event_name == 'schedule'
    
    # 🔐 权限配置：批量处理所需权限
    permissions:
      contents: 'read'    # 读取仓库内容
      id-token: 'write'   # 写入身份令牌
      issues: 'write'     # 写入Issue相关内容
      statuses: 'write'   # 写入状态检查
    
    # 🔗 调用外部工作流：Gemini AI定时Issue处理 (已修复JSON格式问题)
    # 📋 功能：
    #   - 检查过期未回复的Issue
    #   - 自动关闭已解决的Issue
    #   - 更新Issue标签和状态
    #   - 发送提醒通知
    uses: ChenQiWen/gemini-cli-action/.github/workflows/问题定时分类器.yml@main
    secrets: inherit

  # ===============================
  # 🗣️ @abc AI助手命令处理器
  # ===============================
  智能助手命令任务:
    name: 🗣️ 智能助手命令处理器 (@abc)
    # 🎯 条件：评论包含@abc时触发
    if: >-
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '@abc')
    
    # 🔐 权限配置：AI助手交互所需的完整权限
    permissions:
      contents: 'write'       # 写入仓库内容 (可能需要修改代码)
      id-token: 'write'       # 写入身份令牌
      pull-requests: 'write'  # 写入PR相关内容
      issues: 'write'         # 写入Issue相关内容
    
    # 🔗 调用外部工作流：Gemini AI命令行界面 (v0.1.12)
    # 💡 使用方法：
    #   - 在Issue或PR中评论 "@abc 请帮我分析这个bug"
    #   - 在Issue或PR中评论 "@abc 请优化这段代码"
    #   - 在Issue或PR中评论 "@abc 请生成测试用例"
    #   - 在Issue或PR中评论 "@abc fix this issue"
    uses: ChenQiWen/gemini-cli-action/.github/workflows/智能助手命令处理器.yml@main
    with:
      user_request: ${{ github.event.comment.body }}  # 用户请求内容
      issue_number: ${{ github.event.issue.number }}  # Issue编号
      is_pr: ${{ github.event.issue.pull_request != null }}  # 是否为PR
    secrets: inherit

# ===============================================
# 📋 使用说明 & 版本说明
# ===============================================
#
# 🆕 v0.1.12 更新说明：
#   - ✅ 修复了JSON格式解析问题
#   - ✅ 强制JSON输出格式，消除对话式回复
#   - ✅ 优化了Prompt设计，明确输出要求
#   - ✅ 调整了温度设置为0.0，确保一致性
#   - ✅ 限制会话轮次为1，避免对话模式
#   - ✅ 提高了Issue分类的准确性
#   - 🆕 新增智能调度中心，统一AI功能入口
#   - 🆕 新增智能问题修复器，自动生成修复方案
#
# 🤖 AI助手功能：
#   1. 智能调度中心 - 统一AI功能入口和命令路由
#   2. 自动PR审查 - 检查代码质量、安全性、最佳实践
#   3. Issue智能分类 - 自动添加标签、设置优先级
#   4. 智能问题修复 - 自动生成代码修复方案
#   5. 定时维护 - 每日检查和清理Issue状态
#   6. 命令响应 - 使用@abc与AI助手互动
#
# 🔧 配置要求：
#   - GEMINI_API_KEY: Google Gemini API密钥
#   - GITHUB_TOKEN: GitHub访问令牌 (自动提供)
#   - GEMINI.md: 项目根目录的AI配置文件 (可选)
#   - APP_PRIVATE_KEY: GitHub App私钥 (可选，提升权限)
#
# 💡 最佳实践：
#   - 优先使用智能调度中心作为统一入口
#   - 使用@abc命令进行代码审查和修复请求
#   - 创建GEMINI.md文件提供项目特定指导
#   - 让AI助手帮助Issue分类和优先级设置
#   - 定期检查AI生成的建议和标签
#   - 为复杂项目配置GitHub App提升权限
#
# 🐛 故障排除：
#   - ✅ JSON解析错误已修复 (v0.1.12)
#   - 检查GEMINI_API_KEY是否正确配置
#   - 确认仓库权限设置正确
#   - 如果仍有问题，检查工作流日志中的"Raw labels JSON"输出
#   - 确保使用的是最新版本的工作流文件
#
# ===============================================
